# Generated by Django 4.2.16 on 2024-09-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_salesdata_employee_id_alter_salesdata_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AA00', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='default', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='salesdata',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='api.team'),
        ),
    ]
