# Generated by Django 4.2.16 on 2024-09-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_team_description_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='team',
        ),
    ]
