# Generated by Django 4.2.16 on 2024-09-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_salesdata_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
